parameters:
#    esolving_eschool_assistance.example.class: Esolving\Eschool\AssistanceBundle\Example

services:
#    esolving_eschool_assistance.example:
#        class: %esolving_eschool_assistance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
