esolving_eschool_assistanceB_submenu:
    pattern:  /submenu
    defaults: { _controller: EsolvingEschoolAssistanceBundle:Assistance:submenu }

esolving_eschool_assistanceB_register:
    pattern:  /register
    defaults: { _controller: EsolvingEschoolAssistanceBundle:Assistance:register }
